package entis.euler;

public class p2 {
    /** Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

    public static void main(String[] args) {
        // 2 is even valued term that needs to be included in the result.
        // Total is counted by adding even sums, 2 is not sum but a starting number.
        int total = 2;

        int a = 1;
        int b = 2;
        int sum;

        while (b < 4000000) {
            sum = a + b;

            if (sum % 2 == 0 ) {
                total += sum;
            }

            a = b;
            b = sum;
        }


        System.out.println(total); // 4613732
    }
}
